### ISSUE TITLE
you are a life saver!

### ISSUE THREAD

**Issue by soundsbeard** [maikramer/Materialize#21]
i've been using materialize on manjaro with wine for years and it worked just fine.
today i urgently needed to set up traveling laptop with latest ubuntu on board and i've wasted hours trying to run materialize with wine, lutris, PoL with no success.
your build works like a charm! thank you so much!
(feel free to close this issue :smiley:  )

**Comment by maikramer** [comment]
Thanks a lot for recognizing my work. That is better than money for sure. I'm not working on it anymore, just because it works fine. Hope you like using it.
